[package]
name = "wacky_bag_hlist"
version = "0.1.0"
edition = "2024"
authors = ["XNTEABDSC"]
description = "Some tool for frunk::hlist"
license = "MIT"
keywords = [
    "frunk",
    "hlist",
	"variadics"
]
categories = ["rust-patterns"]
repository = "https://github.com/XNTEABDSC/wacky_bag_hlist"

[dependencies]
frunk = "0.4.4"
variadics_please = "2.0.0"

[profile.release]
opt-level = 3
lto = true