[package]
name = "wacky_bag_hlist"
version = "0.4.0"
edition = "2024"
authors = ["XNTEABDSC"]
description = "Some tool/utils for frunk::hlist"
license = "MIT OR Apache-2.0"
keywords = [
    "frunk",
    "hlist",
	"variadics"
]
categories = ["rust-patterns"]
repository = "https://github.com/XNTEABDSC/wacky_bag_hlist"	

[dependencies]
frunk = "0.5.0"
variadics_please = "2.0.0"

[profile.release]
opt-level = 3
lto = true